# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.form.registration:
    class: FormerStudentsBundle\Form\RegistrationType
    tags:
      - { name: form.type, alias: formerstudentsbundle_formerstudent_registration }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
