<?php

namespace FormerStudentsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousChapitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousChapitreRepository extends EntityRepository
{
}
